language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install --upgrade setuptools pip wheel


script:
  - pytest --disable-pytest-warnings
  - python3 setup.py sdist
